### ISSUE TITLE
Increased maximum zoom work only with mouse scroll

### ISSUE THREAD

**Issue by Murdoc84** [m4p3r/exmap-release#2]
I don't know this is problem for everyone but for me it is. Increased maximum zoom range by 50% work only with mouse scroll and doesn't work with Page Up/Down keys. I normally have disabled in UI setting option "Mousewheel Zoom" because i have binded other stuff to mouse wheel :)

**Comment by m4p3r** [comment]
Should be fixed now. Zoom now works with PGUP/PGDWN keys as well. Thanks for the report!
